FROM python:3.11-slim

WORKDIR /app

COPY fetch_job_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY fetch_bronze_api.py .

ENTRYPOINT ["python", "fetch_bronze_api.py"]
